AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function for QuickSight backup

Parameters:
  LambdaExecutionRoleArn:
    Type: String
    Description: ARN of the IAM role to be assumed by Lambda function

Resources:
  QuicksightBackupFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: quicksight-backup2
      Runtime: python3.13
      Handler: lambda_function.lambda_handler
      Timeout: 300
      MemorySize: 128
      Role: !Ref LambdaExecutionRoleArn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "OK"}