AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function for QuickSight backup

Parameters:
  LambdaExecutionRoleArn:
    Type: String
    Description: ARN of the IAM role used by the Lambda function

Resources:
  QuicksightBackupFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: quicksight-backup
      Runtime: python3.13
      Handler: lambda_function.lambda_handler
      Timeout: 300
      MemorySize: 128
      Role: !ImportValue QuickSightBackupRoleArn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "OK"}

Outputs:
  QuickSightBackupFunctionArn:
    Description: ARN of the QuickSight Lambda function
    Value: !GetAtt QuicksightBackupFunction.Arn
    Export:
      Name: QuickSightBackupFunctionArn

  QuickSightBackupFunctionName:
    Description: Name of the QuickSight Lambda function
    Value: !Ref QuicksightBackupFunction
    Export:
      Name: QuickSightBackupFunctionName