name: Deploy Lambda Function

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'
  workflow_dispatch:

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Create deployment package
      run: |
        cd lambda
        zip -r ../function.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Deploy Lambda code
      run: |
        aws lambda update-function-code \
          --function-name quicksight-backup \
          --zip-file fileb://function.zip

    - name: Wait for function update to complete
      run: |
        echo "Waiting for Lambda update to finish..."
        sleep 10

    - name: Update Lambda handler (optional if unchanged)
      run: |
        aws lambda update-function-configuration \
          --function-name quicksight-backup \
          --handler quicksight_backup.main.lambda_handler