name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Create deployment package
      run: |
        cd lambda
        zip -r ../function.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name quicksight-backup \
          --zip-file fileb://function.zip

    - name: Set handler
      run: |
        aws lambda update-function-configuration \
          --function-name quicksight-backup \
          --handler quicksight_backup.main.handler