name: Deploy IAM Role and Policy

on:
  workflow_dispatch:

jobs:
  deploy-iam:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Deploy IAM role and policy via CloudFormation
      run: |
        aws cloudformation deploy \
          --template-file templates/iam-role-policy.yaml \
          --stack-name quicksight-backup-role-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides BackupBucketName=${{ secrets.BACKUP_BUCKET_NAME }}